"""Customer-service question set for telecom / banking / insurance. Intents follow the Bitext taxonomies (the training text
comes from those sets) with Thai descriptions, which is what the models read. Two levels: `business` (which line of
business the message is about) and a per-business `intent`. The shared questions (department, urgency, frustration,
wants_human, wants_refund, has_reference, sentiment) are the same for all three.

Edit the descriptions here when the real call center's wording differs; both labelling and the review tools import this."""

INTENTS = {
    "telecom": {
        "dispute_invoice": "ค่าบริการ/ใบแจ้งหนี้ผิด มีรายการที่ไม่รู้จัก ขอโต้แย้งยอด",
        "invoices": "ขอดู/ขอสำเนาใบแจ้งหนี้ ถามยอดที่ต้องจ่าย",
        "get_compensation": "ขอชดเชย ขอส่วนลดหรือเงินคืนจากปัญหาบริการ",
        "report_poor_signal_coverage": "สัญญาณอ่อน สัญญาณหาย เน็ตช้า ในพื้นที่",
        "report_problem": "แจ้งปัญหาการใช้งานอื่น ๆ โทรไม่ออก เน็ตใช้ไม่ได้ ซิมมีปัญหา",
        "check_excess_data_charges": "ถามค่าบริการส่วนเกิน ค่าเน็ตเกินแพ็กเกจ",
        "check_usage": "ถามยอดใช้งาน เน็ตเหลือเท่าไหร่ นาทีโทรเหลือเท่าไหร่",
        "set_usage_limits": "ตั้งค่าจำกัดการใช้งาน ตั้งเพดานค่าใช้จ่าย",
        "customer_service": "ถามช่องทางติดต่อ เวลาทำการ เบอร์ศูนย์บริการ",
        "human_agent": "ขอคุยกับพนักงานที่เป็นคนจริง",
        "check_mobile_payments": "ถามเรื่องการจ่ายผ่านมือถือ/แอป ยอดที่จ่ายไปแล้ว",
        "payment_methods": "ถามว่ามีวิธีชำระเงินแบบไหนบ้าง",
        "pay": "ต้องการชำระค่าบริการตอนนี้",
        "schedule_payments": "ตั้งค่าจ่ายอัตโนมัติ ตัดบัตร นัดวันชำระ",
        "activate_call_management_services": "เปิดบริการโอนสาย สายเรียกซ้อน ฝากข้อความ ฯลฯ",
        "deactivate_call_management_services": "ปิดบริการโอนสาย สายเรียกซ้อน ฝากข้อความ ฯลฯ",
        "activate_phone": "เปิดใช้งานซิม/เบอร์ใหม่ ลงทะเบียนซิม ขอเปิดสัญญาณคืน ซิมถูกระงับ/หมดอายุแต่อยากใช้เบอร์เดิม",
        "deactivate_phone": "ระงับ/ปิดเบอร์ ระงับซิมชั่วคราว ซิมหาย",
        "activate_roaming": "เปิดโรมมิ่ง ใช้งานต่างประเทศ",
        "check_signal_coverage": "ถามว่าพื้นที่นี้มีสัญญาณไหม ครอบคลุมหรือไม่",
        "install_internet": "ขอติดตั้งอินเทอร์เน็ตบ้าน ไฟเบอร์ นัดช่าง",
        "cancel_plan": "ขอยกเลิกแพ็กเกจ ยกเลิกบริการ",
        "change_plan": "ขอเปลี่ยนแพ็กเกจ อัปเกรด/ดาวน์เกรด",
        "change_provider": "ย้ายค่าย ย้ายเบอร์ไปค่ายอื่น หรือย้ายเข้ามา",
        "check_cancellation_fee": "ถามค่าธรรมเนียมยกเลิกก่อนครบสัญญา",
        "sign_up_for_plan": "สมัครแพ็กเกจใหม่ เปิดเบอร์ใหม่ ขอรหัสสมัครโปร ถามว่ามีโปรไหนบ้าง",
        # run 8 additions (what real Thai users actually ask about; not in Bitext)
        "top_up_problem": "เติมเงินผิดเบอร์ เติมเงินแล้วยอดไม่เข้า ขอดึงเงินเติมคืน โอนเงินในซิม",
        "device_or_equipment": "เครื่อง/อุปกรณ์ ซื้อเครื่องติดสัญญา ผ่อนเครื่อง ประกันเครื่อง เคลมเครื่อง เราเตอร์ กล่องทีวี eSIM ไม่ใช่เรื่องแพ็กเกจ",
        "change_account_details": "เปลี่ยนชื่อผู้จดทะเบียน โอนเบอร์ให้คนอื่น เปลี่ยนเบอร์ติดต่อ แก้ข้อมูลผู้ใช้ ย้ายที่ติดตั้ง",
        "value_added_service": "บริการเสริม/คอนเทนต์ที่หักผ่านเบอร์ (แอปดูหนัง เกม SMS เสียเงิน บริการให้ยืม) สมัคร ยกเลิก ซื้อไม่ผ่าน",
        "complaint": "ร้องเรียนบริการ พนักงาน ช่าง หรือบริษัท",
    },
    "banking": {
        "activate_card": "เปิดใช้งานบัตรใหม่",
        "block_card": "อายัดบัตร บัตรหาย บัตรถูกขโมย",
        "activate_card_international_usage": "เปิดใช้บัตรต่างประเทศ",
        "cancel_card": "ยกเลิกบัตร ปิดบัตร",
        "check_card_annual_fee": "ถามค่าธรรมเนียมรายปีของบัตร ขอยกเว้น",
        "check_current_balance_on_card": "ถามยอดคงเหลือ/วงเงินในบัตร ขอเพิ่ม/ลดวงเงิน",
        "apply_for_mortgage": "ขอสินเชื่อบ้าน/ที่ดิน รีไฟแนนซ์บ้าน ถามผลอนุมัติ/ระยะเวลา",
        "cancel_mortgage": "ยกเลิก/ปิดสินเชื่อบ้าน",
        "apply_for_loan": "ขอสินเชื่อส่วนบุคคล/รถ กู้เงิน ถามเงื่อนไข ผลอนุมัติ ส่งเอกสารเพิ่ม",
        "cancel_loan": "ยกเลิก/ปิดสินเชื่อ โปะหนี้",
        "check_mortgage_payments": "ถามค่างวดบ้าน ยอดผ่อน วันครบกำหนด",
        "check_loan_payments": "ถามค่างวดสินเชื่อ ยอดผ่อน วันครบกำหนด",
        "make_transfer": "โอนเงิน ตั้งโอนล่วงหน้า",
        "cancel_transfer": "ยกเลิกรายการโอน โอนผิด ขอเรียกเงินคืน",
        "check_fees": "ถามค่าธรรมเนียม (โอน ถอน บัญชี)",
        "check_recent_transactions": "ขอดูรายการเดินบัญชี รายการล่าสุด",
        "close_account": "ปิดบัญชี",
        "create_account": "เปิดบัญชีใหม่",
        "human_agent": "ขอคุยกับพนักงานที่เป็นคนจริง",
        "customer_service": "ถามช่องทางติดต่อ เวลาทำการ สาขา/คอลเซ็นเตอร์",
        "recover_swallowed_card": "บัตรถูกตู้ ATM ยึด/กลืน",
        "dispute_ATM_withdrawal": "กดเงินไม่ออกแต่ยอดถูกหัก รายการ ATM ผิด",
        "find_branch": "หาสาขาใกล้เคียง เวลาเปิดสาขา",
        "find_ATM": "หาตู้ ATM ใกล้เคียง",
        "set_up_password": "ตั้ง/เปลี่ยนรหัสผ่าน PIN",
        "get_password": "ลืมรหัสผ่าน/PIN/เลขบัญชี ขอกู้คืน รหัสถูกล็อก",
        # run 8 additions: banking77 groups + what Pantip users ask
        "card_delivery": "บัตรยังไม่ได้รับ ส่งช้า ถามสถานะการส่งบัตร",
        "card_not_working": "บัตรใช้ไม่ได้ รูดไม่ผ่าน ถูกปฏิเสธ บัตรถูกระงับ contactless ไม่ทำงาน",
        "card_replacement": "บัตรหมดอายุ บัตรชำรุด ขอบัตรใหม่ เปลี่ยนประเภทบัตร",
        "apply_for_card": "สมัครบัตรเครดิต/เดบิต/บัตรกดเงินสด บัตรเสริม บัตรเสมือน ถามเงื่อนไขอนุมัติ",
        "card_benefits_or_rewards": "สิทธิประโยชน์บัตร คะแนนสะสม ส่วนลด ผ่อน 0% เลือกบัตรใบไหนดี",
        "transfer_problem": "โอนเงินแล้วปลายทางไม่ได้รับ โอนล่าช้า ยอดค้าง โอนไม่สำเร็จ/ถูกปฏิเสธ",
        "unrecognised_or_wrong_charge": "มีรายการที่ไม่ได้ทำ ถูกหักเงินผิด/ซ้ำ/เกิน ยอดในใบแจ้งหนี้ไม่ตรง",
        "refund_or_reversal": "ขอเงินคืน ยกเลิกรายการซื้อ เงินคืนจากร้านค้ายังไม่เข้า",
        "top_up_or_deposit_problem": "ฝาก/เติมเงินแล้วยอดไม่เข้า ตู้ฝากเงินกินเงิน ถามวิธี/ค่าธรรมเนียม/ลิมิตการเติมเงิน",
        "foreign_currency_and_travel": "ใช้บัตรต่างประเทศ อัตราแลกเปลี่ยน โอนเงินต่างประเทศ สกุลเงินที่รองรับ",
        "identity_verification_kyc": "ยืนยันตัวตน สแกนหน้า NDID ส่งเอกสาร ยืนยันแหล่งที่มาของเงิน ยืนยันไม่ผ่าน",
        "account_suspended_or_fraud": "บัญชีถูกระงับ/อายัด ถูกหลอกโอนเงิน มิจฉาชีพ เงินหายจากบัญชี บัญชีถูกแฮ็ก โทรศัพท์หาย",
        "app_or_login_problem": "แอป/อินเทอร์เน็ตแบงก์เข้าไม่ได้ สมัครแอปไม่ได้ ระบบล่ม เปลี่ยนเครื่อง",
        "statement_or_document": "ขอ statement ใบเสร็จ หนังสือรับรอง ใบแจ้งหนี้ สมุดบัญชีหาย/ขอสมุดใหม่",
        "change_personal_details": "แก้ไขข้อมูลส่วนตัว ที่อยู่ ชื่อ เบอร์โทร อีเมล คำนำหน้า",
        "loan_or_debt_restructuring": "ผ่อนไม่ไหว ค้างชำระ ถูกฟ้อง ปรับโครงสร้างหนี้ รวมหนี้ ขอเลื่อน/ผ่อนผัน ขอส่วนลดปิดหนี้",
        "deposit_or_interest_info": "ถามดอกเบี้ย เงินฝากประจำ สลาก กองทุน หุ้นกู้ ผลิตภัณฑ์ออม/ลงทุนของธนาคาร",
        "payment_or_bill": "จ่ายบิล/ค่าบริการ/ค่างวดผ่านแอปหรือบัตร จ่ายไม่ผ่าน จ่ายผิด จ่ายแล้วยอดไม่ลด/ไม่อัปเดต",
        "complaint": "ร้องเรียนบริการ พนักงาน สาขา หรือธนาคาร",
    },
    "insurance": {
        "information_auto_insurance": "ถามข้อมูลประกันรถยนต์",
        "accept_settlement": "ตกลงรับข้อเสนอค่าสินไหม",
        "file_claim": "ยื่นเคลม แจ้งเคลมใหม่",
        "negotiate_settlement": "ต่อรองค่าสินไหม ขอเพิ่มวงเงินชดเชย",
        "receive_payment": "ถามว่าเงินเคลมจะได้เมื่อไหร่ ยังไม่ได้รับเงินสินไหม",
        "reject_settlement": "ปฏิเสธข้อเสนอค่าสินไหม",
        "track_claim": "ติดตามสถานะเคลม",
        "appeal_denied_insurance_claim": "อุทธรณ์เคลมที่ถูกปฏิเสธ",
        "dispute_invoice": "โต้แย้งใบแจ้งหนี้/ค่าเบี้ยที่ผิด",
        "file_complaint": "ร้องเรียนบริการหรือตัวแทน",
        "agent": "ขอติดต่อตัวแทน/นายหน้าประกัน",
        "customer_service": "ถามช่องทางติดต่อ เวลาทำการ",
        "human_agent": "ขอคุยกับพนักงานที่เป็นคนจริง",
        "insurance_representative": "ขอคุยกับเจ้าหน้าที่ประกันโดยเฉพาะ",
        "change_coverage": "ขอเปลี่ยนความคุ้มครอง",
        "check_coverage": "ถามว่ากรมธรรม์คุ้มครองอะไรบ้าง คุ้มครองกรณีนี้ไหม",
        "downgrade_coverage": "ขอลดความคุ้มครอง/ลดเบี้ย",
        "upgrade_coverage": "ขอเพิ่มความคุ้มครอง",
        "buy_insurance_policy": "ซื้อ/สมัครประกันใหม่",
        "cancellation_fees": "ถามค่าธรรมเนียมยกเลิกกรมธรรม์",
        "cancel_insurance_policy": "ยกเลิกกรมธรรม์ เวนคืน",
        "compare_insurance_policies": "ขอเปรียบเทียบแผนประกัน",
        "general_information": "ถามข้อมูลทั่วไปเกี่ยวกับบริษัทหรือประกัน",
        "information_health_insurance": "ถามข้อมูลประกันสุขภาพ",
        "information_home_insurance": "ถามข้อมูลประกันบ้าน/อัคคีภัย",
        "report_incident": "แจ้งเหตุ อุบัติเหตุ ความเสียหาย",
        "schedule_appointment": "นัดหมาย ตรวจสภาพ พบเจ้าหน้าที่",
        "information_life_insurance": "ถามข้อมูลประกันชีวิต",
        "check_payments": "ถามประวัติ/สถานะการชำระเบี้ย",
        "payment_methods": "ถามวิธีชำระเบี้ย",
        "pay": "ต้องการชำระเบี้ยตอนนี้",
        "report_payment_issue": "ชำระเบี้ยไม่ผ่าน ถูกหักซ้ำ ปัญหาการจ่าย",
        "schedule_payments": "ตั้งค่าจ่ายเบี้ยอัตโนมัติ นัดวันชำระ",
        "information_pet_insurance": "ถามข้อมูลประกันสัตว์เลี้ยง",
        "change_personal_details": "แก้ไขข้อมูลส่วนตัวในกรมธรรม์ ที่อยู่ ผู้รับผลประโยชน์",
        "calculate_insurance_quote": "ขอใบเสนอราคา คำนวณเบี้ย",
        "check_rates": "ถามอัตราเบี้ย ราคาแผน",
        "renew_insurance_policy": "ต่ออายุกรมธรรม์",
        "information_travel_insurance": "ถามข้อมูลประกันเดินทาง",
        # run 8 addition
        "policy_document_not_received": "ยังไม่ได้รับกรมธรรม์/เลขกรมธรรม์ กรมธรรม์ยังไม่ออก ขอสำเนา ถามสถานะกรมธรรม์",
    },
}
# run 8: map banking77's 77 labels (data/cs2/banking77_th.jsonl) onto the banking list above
BANKING77_TO_CS = {
    "activate_my_card": "activate_card", "age_limit": "create_account", "apple_pay_or_google_pay": "payment_or_bill", "atm_support": "find_ATM",
    "automatic_top_up": "top_up_or_deposit_problem", "balance_not_updated_after_bank_transfer": "transfer_problem",
    "balance_not_updated_after_cheque_or_cash_deposit": "top_up_or_deposit_problem", "beneficiary_not_allowed": "make_transfer",
    "cancel_transfer": "cancel_transfer", "card_about_to_expire": "card_replacement", "card_acceptance": "card_not_working", "card_arrival": "card_delivery",
    "card_delivery_estimate": "card_delivery", "card_linking": "activate_card", "card_not_working": "card_not_working", "card_payment_fee_charged": "check_fees",
    "card_payment_not_recognised": "unrecognised_or_wrong_charge", "card_payment_wrong_exchange_rate": "foreign_currency_and_travel",
    "card_swallowed": "recover_swallowed_card", "cash_withdrawal_charge": "check_fees", "cash_withdrawal_not_recognised": "dispute_ATM_withdrawal",
    "change_pin": "set_up_password", "compromised_card": "block_card", "contactless_not_working": "card_not_working", "country_support": "foreign_currency_and_travel",
    "declined_card_payment": "card_not_working", "declined_cash_withdrawal": "dispute_ATM_withdrawal", "declined_transfer": "transfer_problem",
    "direct_debit_payment_not_recognised": "unrecognised_or_wrong_charge", "disposable_card_limits": "apply_for_card", "edit_personal_details": "change_personal_details",
    "exchange_charge": "foreign_currency_and_travel", "exchange_rate": "foreign_currency_and_travel", "exchange_via_app": "foreign_currency_and_travel",
    "extra_charge_on_statement": "unrecognised_or_wrong_charge", "failed_transfer": "transfer_problem", "fiat_currency_support": "foreign_currency_and_travel",
    "get_disposable_virtual_card": "apply_for_card", "get_physical_card": "apply_for_card", "getting_spare_card": "apply_for_card", "getting_virtual_card": "apply_for_card",
    "lost_or_stolen_card": "block_card", "lost_or_stolen_phone": "account_suspended_or_fraud", "order_physical_card": "apply_for_card", "passcode_forgotten": "get_password",
    "pending_card_payment": "transfer_problem", "pending_cash_withdrawal": "dispute_ATM_withdrawal", "pending_top_up": "top_up_or_deposit_problem", "pending_transfer": "transfer_problem",
    "pin_blocked": "set_up_password", "receiving_money": "make_transfer", "Refund_not_showing_up": "refund_or_reversal", "request_refund": "refund_or_reversal",
    "reverted_card_payment?": "refund_or_reversal", "supported_cards_and_currencies": "foreign_currency_and_travel", "terminate_account": "close_account",
    "top_up_by_bank_transfer_charge": "check_fees", "top_up_by_card_charge": "check_fees", "top_up_by_cash_or_cheque": "top_up_or_deposit_problem",
    "top_up_failed": "top_up_or_deposit_problem", "top_up_limits": "top_up_or_deposit_problem", "top_up_reverted": "top_up_or_deposit_problem",
    "topping_up_by_card": "top_up_or_deposit_problem", "transaction_charged_twice": "unrecognised_or_wrong_charge", "transfer_fee_charged": "check_fees",
    "transfer_into_account": "make_transfer", "transfer_not_received_by_recipient": "transfer_problem", "transfer_timing": "make_transfer",
    "unable_to_verify_identity": "identity_verification_kyc", "verify_my_identity": "identity_verification_kyc", "verify_source_of_funds": "identity_verification_kyc",
    "verify_top_up": "top_up_or_deposit_problem", "virtual_card_not_working": "card_not_working", "visa_or_mastercard": "apply_for_card",
    "why_verify_identity": "identity_verification_kyc", "wrong_amount_of_cash_received": "dispute_ATM_withdrawal",
    "wrong_exchange_rate_for_cash_withdrawal": "foreign_currency_and_travel",
}
INTENTS["ecommerce"] = {  # drafted from the real messages (real_eval/intents_proposal.md); Bitext's 27 map onto it (BITEXT_TO_ECOM)
    "track_order": "ของยังไม่ถึง ถามสถานะพัสดุ tracking ผิดปกติ ส่งช้า",
    "cancel_order": "ขอยกเลิกออเดอร์ สั่งผิด เปลี่ยนใจ ระบบไม่ให้ยกเลิก ถามค่าธรรมเนียมยกเลิก",
    "change_order": "แก้จำนวน เปลี่ยนรุ่น/สี/ไซส์ ก่อนส่ง",
    "change_shipping": "เปลี่ยนที่อยู่จัดส่ง เลื่อนวันส่ง ขอส่งด่วน ถามตัวเลือก/ระยะเวลาจัดส่ง",
    "return_item": "ขอคืนสินค้า ถามเงื่อนไขการคืน ไซส์ไม่พอดี ไม่ถูกใจ",
    "damaged_or_wrong_item": "ของชำรุด กล่องบุบ ของหมดอายุ ได้ของไม่ตรง ได้ไม่ครบ",
    "wrong_delivery": "ส่งผิดที่อยู่ ส่งไปที่อยู่เก่า ของถูกตีกลับ ได้ของซ้ำ/เกิน",
    "refund_status": "ถามว่าเงินคืนถึงไหน คืนช้า คืนผิดบัญชี ถามนโยบายคืนเงิน",
    "refund_request": "ขอเงินคืน ขอส่วนต่าง ยกเลิกแล้วยังโดนหัก",
    "payment_issue": "จ่ายไม่ผ่าน ตัดเงินแต่ไม่มีออเดอร์ ผ่อนชำระ ถามวิธีชำระเงิน",
    "invoice_or_document": "ขอใบเสร็จ ใบกำกับภาษี ใบแจ้งหนี้ เอกสารยืนยัน สลิป",
    "promotion_or_price": "ถามโปรโมชั่น โค้ดส่วนลด ราคาลดหลังสั่ง ของแถมไม่มา จดหมายข่าว",
    "product_question": "ถามสต็อก สี ไซส์ วิธีใช้ สเปก ประกัน ศูนย์ซ่อม",
    "place_order": "ต้องการสั่งซื้อ ช่วยสั่งให้",
    "account_issue": "ล็อกอินไม่ได้ ลืมรหัส บัญชีถูกระงับ สมัคร/ลบ/แก้ไขบัญชี เปลี่ยนประเภทบัญชี",
    "loyalty_points": "คะแนนสะสม แลกของไม่ได้ คูปอง",
    "app_or_website_bug": "แอป/เว็บล่ม กดไม่ได้ หน้าค้าง",
    "case_status": "ถามความคืบหน้าเคส/เรื่องที่แจ้งไว้ ขอเปิดเคส ถามเลขเคส",
    "complaint_service": "ร้องเรียนบริการ แชทตอบช้า พนักงานไม่สุภาพ คุณภาพต่ำกว่าโฆษณา รีวิว",
    "contact_or_callback": "ขอคุยกับพนักงาน ขอเบอร์/ช่องทางติดต่อ ขอให้โทรกลับ",
    "praise": "ชม ขอบคุณ",
}
BITEXT_TO_ECOM = {  # the 27 Bitext customer-support intents (runs 4-5 training labels) -> the e-commerce list above
    "track_order": "track_order", "cancel_order": "cancel_order", "check_cancellation_fee": "cancel_order", "change_order": "change_order",
    "change_shipping_address": "change_shipping", "set_up_shipping_address": "change_shipping", "delivery_options": "change_shipping",
    "delivery_period": "change_shipping", "get_refund": "refund_request", "track_refund": "refund_status", "check_refund_policy": "refund_status",
    "payment_issue": "payment_issue", "check_payment_methods": "payment_issue", "get_invoice": "invoice_or_document", "check_invoice": "invoice_or_document",
    "newsletter_subscription": "promotion_or_price", "place_order": "place_order", "create_account": "account_issue", "delete_account": "account_issue",
    "edit_account": "account_issue", "switch_account": "account_issue", "recover_password": "account_issue", "registration_problems": "account_issue",
    "complaint": "complaint_service", "review": "complaint_service", "contact_customer_service": "contact_or_callback", "contact_human_agent": "contact_or_callback",
}
OTHER = "ไม่เข้าข่ายข้อใดข้างต้น หรือไม่ใช่เรื่องติดต่อฝ่ายบริการลูกค้า"
BUSINESS_Q = {"type": "choice", "instructions": "ข้อความนี้เกี่ยวกับบริการของธุรกิจใด",
              "criteria": {"telecom": "ค่ายมือถือ อินเทอร์เน็ต แพ็กเกจ ซิม สัญญาณ", "banking": "ธนาคาร บัตร บัญชี โอนเงิน สินเชื่อ ATM",
                           "insurance": "ประกัน กรมธรรม์ เคลม ความคุ้มครอง เบี้ย", "ecommerce": "ร้านค้าออนไลน์ ออเดอร์ สินค้า จัดส่ง คืนของ",
                           "other": "ไม่ใช่ทั้งสี่อย่าง หรือไม่ใช่เรื่องบริการลูกค้า"}}
SHARED = {
    "department": {"type": "choice", "instructions": "ควรส่งเรื่องนี้ให้ทีมใดรับผิดชอบ",
                   "criteria": {"billing": "ค่าบริการ ใบแจ้งหนี้ การชำระเงิน เบี้ย ค่าธรรมเนียม", "technical": "ใช้งานไม่ได้ สัญญาณ แอป ระบบขัดข้อง ติดตั้ง",
                                "account": "บัญชี บัตร รหัสผ่าน ข้อมูลส่วนตัว กรมธรรม์", "sales": "สมัคร ซื้อ เปลี่ยนแพ็กเกจ/แผน ขอใบเสนอราคา",
                                "claims": "เคลม สินไหม อุบัติเหตุ ชดเชย", "support": "ร้องเรียน ขอคุยกับพนักงาน ถามข้อมูลทั่วไป"}},
    "urgency": {"type": "score", "instructions": "เรื่องนี้เร่งด่วนแค่ไหน",
                "criteria": ["ไม่รีบ ถามข้อมูลทั่วไป", "ควรตอบภายในวันนี้", "ด่วน ลูกค้าเสียหายหรือใช้งานไม่ได้อยู่ (บัตรหาย เน็ตล่ม อุบัติเหตุ)"]},
    "frustration": {"type": "score", "instructions": "ลูกค้าไม่พอใจแค่ไหน", "criteria": ["ใจเย็น", "หงุดหงิดแต่สุภาพ", "โกรธมาก"]},
    "wants_human": {"type": "noul", "instructions": "ลูกค้าต้องการคุยกับพนักงานที่เป็นคนจริงหรือไม่"},
    "wants_refund": {"type": "noul", "instructions": "ลูกค้าขอเงินคืน ชดเชย หรือโต้แย้งยอดที่ถูกเรียกเก็บหรือไม่"},
    "has_reference": {"type": "noul", "instructions": "ข้อความระบุเลขอ้างอิง เช่น เลขบัญชี เลขกรมธรรม์ เลขเคลม เลขใบแจ้งหนี้ หรือเบอร์โทร หรือไม่"},
    "sentiment": {"type": "choice", "instructions": "อารมณ์โดยรวมของข้อความ",
                  "criteria": {"positive": "ชม พอใจ ดีใจ", "neutral": "เล่าเฉย ๆ ให้ข้อมูล", "negative": "บ่น ไม่พอใจ โกรธ", "question": "ถามคำถาม ขอข้อมูล"}},
}


def intent_question(business, with_other=True):
    crit = dict(INTENTS[business])
    if with_other:
        crit["other"] = OTHER
    return {"type": "choice", "instructions": "ลูกค้าต้องการอะไร", "criteria": crit}


def question_set(business, with_other=True):
    """The full set for one business: business + intent (that business's list) + shared questions."""
    return {"business": BUSINESS_Q, "intent": intent_question(business, with_other), **SHARED}


ORDER = ["business", "intent", "department", "urgency", "frustration", "wants_human", "wants_refund", "has_reference", "sentiment"]
